<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126063249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, favorite_user_id INT NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68C58ED9FA3A7DFB ON favorite (favorite_user_id)');
        $this->addSql('CREATE INDEX IDX_68C58ED9D4619D1A ON favorite (listing_id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9FA3A7DFB FOREIGN KEY (favorite_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_listing DROP CONSTRAINT fk_930d56dea76ed395');
        $this->addSql('ALTER TABLE user_listing DROP CONSTRAINT fk_930d56ded4619d1a');
        $this->addSql('DROP TABLE user_listing');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_listing (user_id INT NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (user_id, listing_id))');
        $this->addSql('CREATE INDEX idx_930d56ded4619d1a ON user_listing (listing_id)');
        $this->addSql('CREATE INDEX idx_930d56dea76ed395 ON user_listing (user_id)');
        $this->addSql('ALTER TABLE user_listing ADD CONSTRAINT fk_930d56dea76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_listing ADD CONSTRAINT fk_930d56ded4619d1a FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9FA3A7DFB');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9D4619D1A');
        $this->addSql('DROP TABLE favorite');
    }
}
