<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126060705 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE apartment_listing (balcony BOOLEAN NOT NULL, number_of_rooms INT NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, total_price DOUBLE PRECISION NOT NULL, listing_id INT NOT NULL, booker_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDED4619D1A ON booking (listing_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE8B7E4006 ON booking (booker_id)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE house_listing (garden_size DOUBLE PRECISION NOT NULL, has_garage BOOLEAN NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C53D045FD4619D1A ON image (listing_id)');
        $this->addSql('CREATE TABLE listing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, price_per_night DOUBLE PRECISION NOT NULL, capacity INT NOT NULL, owner_id INT DEFAULT NULL, category_id INT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CB0048D47E3C61F9 ON listing (owner_id)');
        $this->addSql('CREATE INDEX IDX_CB0048D412469DE2 ON listing (category_id)');
        $this->addSql('CREATE TABLE listing_option (listing_id INT NOT NULL, option_id INT NOT NULL, PRIMARY KEY (listing_id, option_id))');
        $this->addSql('CREATE INDEX IDX_BE7E2163D4619D1A ON listing_option (listing_id)');
        $this->addSql('CREATE INDEX IDX_BE7E2163A7C41D6F ON listing_option (option_id)');
        $this->addSql('CREATE TABLE option_listing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8157AA0FA76ED395 ON profile (user_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, listing_id INT DEFAULT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C6D4619D1A ON review (listing_id)');
        $this->addSql('CREATE INDEX IDX_794381C6F675F31B ON review (author_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, avatar VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE user_listing (user_id INT NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (user_id, listing_id))');
        $this->addSql('CREATE INDEX IDX_930D56DEA76ED395 ON user_listing (user_id)');
        $this->addSql('CREATE INDEX IDX_930D56DED4619D1A ON user_listing (listing_id)');
        $this->addSql('CREATE TABLE user_option (user_id INT NOT NULL, option_id INT NOT NULL, PRIMARY KEY (user_id, option_id))');
        $this->addSql('CREATE INDEX IDX_3FD41B8DA76ED395 ON user_option (user_id)');
        $this->addSql('CREATE INDEX IDX_3FD41B8DA7C41D6F ON user_option (option_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE apartment_listing ADD CONSTRAINT FK_4736A65EBF396750 FOREIGN KEY (id) REFERENCES listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE8B7E4006 FOREIGN KEY (booker_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE house_listing ADD CONSTRAINT FK_5FD7CEC9BF396750 FOREIGN KEY (id) REFERENCES listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045FD4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D47E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE listing_option ADD CONSTRAINT FK_BE7E2163D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE listing_option ADD CONSTRAINT FK_BE7E2163A7C41D6F FOREIGN KEY (option_id) REFERENCES option_listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_listing ADD CONSTRAINT FK_930D56DEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_listing ADD CONSTRAINT FK_930D56DED4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_option ADD CONSTRAINT FK_3FD41B8DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_option ADD CONSTRAINT FK_3FD41B8DA7C41D6F FOREIGN KEY (option_id) REFERENCES option_listing (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE apartment_listing DROP CONSTRAINT FK_4736A65EBF396750');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDED4619D1A');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE8B7E4006');
        $this->addSql('ALTER TABLE house_listing DROP CONSTRAINT FK_5FD7CEC9BF396750');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045FD4619D1A');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D47E3C61F9');
        $this->addSql('ALTER TABLE listing DROP CONSTRAINT FK_CB0048D412469DE2');
        $this->addSql('ALTER TABLE listing_option DROP CONSTRAINT FK_BE7E2163D4619D1A');
        $this->addSql('ALTER TABLE listing_option DROP CONSTRAINT FK_BE7E2163A7C41D6F');
        $this->addSql('ALTER TABLE profile DROP CONSTRAINT FK_8157AA0FA76ED395');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6D4619D1A');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6F675F31B');
        $this->addSql('ALTER TABLE user_listing DROP CONSTRAINT FK_930D56DEA76ED395');
        $this->addSql('ALTER TABLE user_listing DROP CONSTRAINT FK_930D56DED4619D1A');
        $this->addSql('ALTER TABLE user_option DROP CONSTRAINT FK_3FD41B8DA76ED395');
        $this->addSql('ALTER TABLE user_option DROP CONSTRAINT FK_3FD41B8DA7C41D6F');
        $this->addSql('DROP TABLE apartment_listing');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE house_listing');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE listing');
        $this->addSql('DROP TABLE listing_option');
        $this->addSql('DROP TABLE option_listing');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_listing');
        $this->addSql('DROP TABLE user_option');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
